version: '3.9'
services:
  web:
    image: srv-config:latest
    networks:
      - schambeck-overlay
    environment:
      - DISCOVERY_URI=http://discovery:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_VIRTUAL_HOST=
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
    ports:
      - target: 8888
        published: 8888
networks:
  schambeck-overlay:
    external: true
