version: '3.9'
services:
  web:
    image: srv-config:latest
    networks:
      schambeck-net:
        aliases:
          - srv-config
    environment:
      - DISCOVERY_URI=http://srv-discovery:8761/eureka
      - SPRING_RABBITMQ_HOST=srv-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_VIRTUAL_HOST=
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
networks:
  schambeck-net:
    external: true
