version: '3.9'
services:
  web:
    image: srv-config:latest
    networks:
      schambeck-net:
        aliases:
          - srv-config
    environment:
      - DISCOVERY_URI=http://srv-discovery:8761/eureka
      - SPRING_RABBITMQ_HOST=srv-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_VIRTUAL_HOST=
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  discovery:
    image: mschambeck/srv-discovery:latest
    networks:
      schambeck-net:
        aliases:
          - srv-discovery
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    ports:
      - target: 8761
        published: 8761
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      schambeck-net:
        aliases:
          - srv-rabbitmq
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    ports:
      - target: 5672
        published: 5672
      - target: 15672
        published: 15672
networks:
  schambeck-net:
    name: schambeck-net
    driver: overlay
